### PR TITLE
Introduced 'Freeform Debug Info'

### PR DESCRIPTION
**Pull request by SiliconOrchid**
Introduced 'Freeform Debug Info' - intended as a mechanism for developers to include their own adhoc debug data, for inclusion into the GOAP-NodeViewer.

The intent is to allow developers to drop in whatever adhoc agent-specific data they would like & have it displayed inline with the existing Node Viewer.

This PR is based upon the developer building their own string of debug info - there may be a more modular way of approaching this, but as a relatively quick way to get a desired result, this works.

Changes include:

* private string in `AgentBehaviour` to store the content of the user-created-message (including update to interface)
* revision of `AgentDataDrawer` to draw a new minor-heading and the user-create-message
* revision of the `ComplexAgentBrain` in demo, to show how developers could add in their own custom debug messages. 

The change to `ComplexAgentBrain` uses a coroutine to reduce the update frequency (i.e. it is not on the update loop) - this may be a candidate for a refactor if this isn't in-keeping with any preferred coding style for scheduled tasks?

image

### CODE REVIEW

**Comment by crashkonijn** [comment]
Hey @SiliconOrchid,

Thanks for the PR! I really like the idea, but I think we can make a more modular setup using UI Toolkit.

If that's not possible I think it'd be better to add an interface implementation on the set, it's not efficient to update the text of each agent when (n)one is displayed.

**Comment by SiliconOrchid** [comment]
absolutely fine - I'm happy for this PR to be fully rejected and instead be considered as a way to describe a feature request! :-D   Should this be closed and added instead as a new issue?  

The intent here is that:   As a consuming developer of the package, it would be helpful for me to display various data-points of debugging information and that I would like a good degree of control over which items these are and perhaps how they are formatted.

Shooting from the hip:   I feel like there should be some sort of interface for defining these messages, and to then register them centrally (for each agent).   I can't quite think how best to generate the messages on-the-fly .... I feel like there is some need to register a delegated function (of some form) from the place where the developer is working with that data (not necessarily the brain, as I did in the PR).   Something along the lines of "here is reference to data point" + "here is the string template I want to use" ... "now go and generate the various messages async according to some scheduling handler" etc

**Comment by crashkonijn** [comment]
Totally valid points!

I think creating an issue with a description would indeed be best for now. Let's discuss the best solution on Discord some time.

PS: I was thinking something along the lines of this:

```csharp
public interface IAgentDebugger {
    public string GetInfo(IMonoAgent agent, IComponentReferences references);
}
```

**Comment by SiliconOrchid** [comment]
Closing PR, as the idea have been transferred to [Issue 40](https://github.com/crashkonijn/GOAP/issues/40)

**Pull request closed without merging**
